#DEV

#server:
# port: 8082
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/development #change this to your database url
#    password: root #change this to your database username
#    username: root #change this to your database password
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#  jmx:
#    enabled: true

#PROD
# This below shoul be executed for mysql 8
#  ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'yNewPass4!';
#  FLUSH PRIVILEGES;

server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/development #change this to your database url
    password: yNewPass4! #change this to your database username
    username: root #change this to your database password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: true


#TEST mariaDB
#server:
# port: 8082
#
#
#spring:
#  datasource:
#    url: jdbc:mariadb://localhost:3306/development #change this to your database url
#    password: root #change this to your database username
#    username: root #change this to your database password
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MariaDBDialect
#  jmx:
#    enabled: true


